// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PresupuestitoBack.DataAccess;

#nullable disable

namespace PresupuestitoBack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241105221527_fixMigration")]
    partial class fixMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PresupuestitoBack.Models.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("BudgetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetId"));

                    b.Property<string>("BudgetStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int?>("ClientHistoryId")
                        .HasColumnType("INT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("DATE");

                    b.Property<DateTime?>("DeadLine")
                        .HasColumnType("DATE");

                    b.Property<string>("DescriptionBudget")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(400)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("BudgetId");

                    b.HasIndex("ClientHistoryId");

                    b.HasIndex("ClientId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("CategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ClientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<int>("PersonId")
                        .HasColumnType("INT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ClientId");

                    b.HasIndex("PersonId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.ClientHistory", b =>
                {
                    b.Property<int>("ClientHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ClientHistoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientHistoryId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("INT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ClientHistoryId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientsHistorys");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Cost", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("CostId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostId"));

                    b.Property<decimal>("CostValue")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CostId");

                    b.ToTable("Costs");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("EmployeeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("PersonId")
                        .HasColumnType("INT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeId");

                    b.HasIndex("PersonId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.EmployeeHistory", b =>
                {
                    b.Property<int>("EmployeeHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("EmployeeHistoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeHistoryId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeHistoryId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeHistories");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.FixedCost", b =>
                {
                    b.Property<int>("FixedCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("FixedCostId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FixedCostId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateOnly>("DateCharged")
                        .HasColumnType("DATE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("INT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("INT");

                    b.HasKey("FixedCostId");

                    b.ToTable("FixedCost");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("InvoiceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("BIT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INT");

                    b.HasKey("InvoiceId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.InvoiceItem", b =>
                {
                    b.Property<int>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("InvoiceItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceItemId"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("InvoiceItemId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("MaterialId");

                    b.ToTable("InvoicesItems");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("INT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("WorkId")
                        .HasColumnType("INT");

                    b.HasKey("ItemId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("WorkId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("MaterialId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("MaterialBrand")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("MaterialColor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("MaterialDescription")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(400)");

                    b.Property<string>("MaterialMeasure")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("MaterialUnitMeasure")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("SubCategoryMaterialId")
                        .HasColumnType("INT");

                    b.HasKey("MaterialId");

                    b.HasIndex("SubCategoryMaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("PaymentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("BudgetId")
                        .HasColumnType("INT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE");

                    b.Property<string>("DescriptionPayment")
                        .IsRequired()
                        .HasColumnType("VARCHAR(400)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PaymentId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.PaymentBudget", b =>
                {
                    b.Property<int>("PaymentBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("PaymentBudgetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentBudgetId"));

                    b.Property<int>("BudgetId")
                        .HasColumnType("INT");

                    b.Property<int>("PaymentId")
                        .HasColumnType("INT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PaymentBudgetId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentsBudget");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.PaymentInvoice", b =>
                {
                    b.Property<int>("PaymentInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("PaymentInvoice");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentInvoiceId"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INT");

                    b.Property<int>("PaymentId")
                        .HasColumnType("INT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PaymentInvoiceId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentsInvoice");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.PaymentSalary", b =>
                {
                    b.Property<int>("PaymentSalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("PaymentSalaryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentSalaryId"));

                    b.Property<int>("PaymentId")
                        .HasColumnType("INT");

                    b.Property<int>("SalaryId")
                        .HasColumnType("INT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PaymentSalaryId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("SalaryId");

                    b.ToTable("PaymentsSalary");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("PersonId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Salary", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("SalaryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("PaymentId")
                        .HasColumnType("INT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("SalaryId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.SubCategoryMaterial", b =>
                {
                    b.Property<int>("SubCategoryMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("SubCategoryMaterialId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryMaterialId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("INT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("SubCategoryMaterialId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("SupplierId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<int>("PersonId")
                        .HasColumnType("INT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("SupplierId");

                    b.HasIndex("PersonId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.SupplierHistory", b =>
                {
                    b.Property<int>("SupplierHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("SupplierHistoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierHistoryId"));

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INT");

                    b.HasKey("SupplierHistoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierHistories");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Work", b =>
                {
                    b.Property<int>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("WorkId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkId"));

                    b.Property<int>("BudgetId")
                        .HasColumnType("INT");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("DATE");

                    b.Property<int>("EstimatedHoursWorked")
                        .HasColumnType("INT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("WorkStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.HasKey("WorkId");

                    b.HasIndex("BudgetId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Budget", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.ClientHistory", null)
                        .WithMany("Budgets")
                        .HasForeignKey("ClientHistoryId");

                    b.HasOne("PresupuestitoBack.Models.Client", "Oclient")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oclient");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Client", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Person", "OPerson")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OPerson");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.ClientHistory", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Client", "Oclient")
                        .WithMany("ClientsHistory")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oclient");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Employee", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Person", "OPerson")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OPerson");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.EmployeeHistory", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Employee", "OEmployee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OEmployee");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Invoice", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Supplier", "OSupplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OSupplier");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.InvoiceItem", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Invoice", "OInvoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PresupuestitoBack.Models.Material", "OMaterial")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OInvoice");

                    b.Navigation("OMaterial");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Item", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Material", "OMaterial")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PresupuestitoBack.Models.Work", "OWork")
                        .WithMany("OMaterials")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OMaterial");

                    b.Navigation("OWork");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Material", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.SubCategoryMaterial", "OSubcategoryMaterial")
                        .WithMany()
                        .HasForeignKey("SubCategoryMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OSubcategoryMaterial");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Payment", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Budget", "OBudget")
                        .WithMany("Payments")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PresupuestitoBack.Models.Invoice", "OInvoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OBudget");

                    b.Navigation("OInvoice");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.PaymentBudget", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Budget", "OBudget")
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PresupuestitoBack.Models.Payment", "OPayment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OBudget");

                    b.Navigation("OPayment");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.PaymentInvoice", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Invoice", "OInvoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PresupuestitoBack.Models.Payment", "OPayment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OInvoice");

                    b.Navigation("OPayment");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.PaymentSalary", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Payment", "OPayment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PresupuestitoBack.Models.Salary", "OSalary")
                        .WithMany()
                        .HasForeignKey("SalaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OPayment");

                    b.Navigation("OSalary");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Salary", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Payment", "OPayment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OPayment");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.SubCategoryMaterial", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Category", "OCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OCategory");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Supplier", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Person", "OPerson")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OPerson");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.SupplierHistory", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Supplier", "Osupplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osupplier");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Work", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Budget", "Budget")
                        .WithMany("Works")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Budget", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Client", b =>
                {
                    b.Navigation("ClientsHistory");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.ClientHistory", b =>
                {
                    b.Navigation("Budgets");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Work", b =>
                {
                    b.Navigation("OMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
